baseurl = "/"
relativeURLs = true
uglyURLs = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Main"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"
[[menu.main]]
name = "books2022"
url = "/books2022.html"
weight = 2
[[menu.main]]
name = "books2021"
url = "/books2021.html"
weight = 3
[[menu.main]]
name = "books2020"
url = "/books2020.html"
weight = 4
# [[menu.main]]
# name = "Tags"
# url = "/tags/"
# weight = 2
#[[menu.feed]]
#name = "Subscribe"
#url = "/index.xml"



[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
#footer = "Arham's Website | [Twitter](https://twitter.com/arhamcc) | [Github](https://github.com/arhammukhtar) | [Old Blog](https://blog.arhamt.com)"
footer = "Arham's Website | [Twitter](https://twitter.com/arhamcc)"